services:
  web:
    image: nginx:latest
    container_name: web_container
    networks:
      - webnet
    ports:
      - "8080:80"

  app:
    image: apache-atc:latest
    container_name: app_container
    networks:
      - webnet
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - dbnet

networks:
  webnet:
    driver: bridge
  dbnet:
    driver: bridge